name: "构建JD测试版"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: 构建JD测试版
    env:
      IMAGE_NAME: jd
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: 设置QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      -
        name: 设置Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: 登陆Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: 构建v4镜像并推送
        id: docker_build_1
        uses: docker/build-push-action@v2
        with:
          pull: true
          push: true
          context: ${IMAGE_NAME}
          file: ${IMAGE_NAME}/v4.unstable.Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          tags: ${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}:v4-unstable
          build-args: |
            JD_SHELL_KEY=${{ secrets.JD_SHELL_KEY }}
            JD_SCRIPTS_KEY=${{ secrets.JD_SCRIPTS_KEY }}
      -
        name: 构建v4-bot镜像并推送
        id: docker_build_2
        uses: docker/build-push-action@v2
        with:
          pull: false
          push: true
          context: ${IMAGE_NAME}
          file: ${IMAGE_NAME}/v4-bot.unstable.Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          tags: ${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}:v4-bot-unstable
