name: "构建Python"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: 构建Python
    env:
      IMAGE_NAME: python
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Build and publish image
        uses: ilteoood/docker_buildx@master
        with:
          publish: true
          imageName: ${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}
          dockerFile: ${IMAGE_NAME}/Dockerfile
          platform: linux/amd64,linux/arm64/v8,linux/arm/v7
          tag: latest
          dockerUser: ${{ secrets.DOCKER_USERNAME }}
          dockerPassword: ${{ secrets.DOCKER_PASSWORD }}
          context: ${IMAGE_NAME}
